apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.backend.fullname" . }}-secret
  labels:
    {{- include "todo-chatbot.backend.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.backend.secretKey | default (randAlphaNum 32) | b64enc | quote }}